package com.skillforge.server.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.Instant;

/**
 * A Java class generated by Code Agent and compiled in-process into a {@code BuiltInMethod}
 * implementation. Lifecycle: pending_review → compiled → active / rejected.
 *
 * <p>Only rows with status = {@code active} are loaded into {@code BuiltInMethodRegistry} under
 * the {@code agent.*} namespace at startup.
 */
@Entity
@Table(name = "t_compiled_method")
@EntityListeners(AuditingEntityListener.class)
public class CompiledMethodEntity {

    public static final String STATUS_PENDING_REVIEW = "pending_review";
    public static final String STATUS_COMPILED = "compiled";
    public static final String STATUS_ACTIVE = "active";
    public static final String STATUS_REJECTED = "rejected";

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Unique lookup key, must start with {@code "agent."}. */
    @Column(nullable = false, unique = true, length = 128)
    private String ref;

    @Column(name = "display_name", length = 256)
    private String displayName;

    @Column(columnDefinition = "TEXT")
    private String description;

    @Column(name = "source_code", nullable = false, columnDefinition = "TEXT")
    private String sourceCode;

    @Column(name = "compiled_class_bytes")
    private byte[] compiledClassBytes;

    @Column(nullable = false, length = 16)
    private String status = STATUS_PENDING_REVIEW;

    @Column(name = "compile_error", columnDefinition = "TEXT")
    private String compileError;

    @Column(name = "args_schema", columnDefinition = "TEXT")
    private String argsSchema;

    @Column(name = "generated_by_session_id", length = 36)
    private String generatedBySessionId;

    @Column(name = "generated_by_agent_id")
    private Long generatedByAgentId;

    @Column(name = "reviewed_by_user_id")
    private Long reviewedByUserId;

    @CreatedDate
    @Column(name = "created_at", nullable = false)
    private Instant createdAt;

    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    public CompiledMethodEntity() {
    }

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getRef() { return ref; }
    public void setRef(String ref) { this.ref = ref; }

    public String getDisplayName() { return displayName; }
    public void setDisplayName(String displayName) { this.displayName = displayName; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public String getSourceCode() { return sourceCode; }
    public void setSourceCode(String sourceCode) { this.sourceCode = sourceCode; }

    public byte[] getCompiledClassBytes() { return compiledClassBytes; }
    public void setCompiledClassBytes(byte[] compiledClassBytes) { this.compiledClassBytes = compiledClassBytes; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }

    public String getCompileError() { return compileError; }
    public void setCompileError(String compileError) { this.compileError = compileError; }

    public String getArgsSchema() { return argsSchema; }
    public void setArgsSchema(String argsSchema) { this.argsSchema = argsSchema; }

    public String getGeneratedBySessionId() { return generatedBySessionId; }
    public void setGeneratedBySessionId(String generatedBySessionId) { this.generatedBySessionId = generatedBySessionId; }

    public Long getGeneratedByAgentId() { return generatedByAgentId; }
    public void setGeneratedByAgentId(Long generatedByAgentId) { this.generatedByAgentId = generatedByAgentId; }

    public Long getReviewedByUserId() { return reviewedByUserId; }
    public void setReviewedByUserId(Long reviewedByUserId) { this.reviewedByUserId = reviewedByUserId; }

    public Instant getCreatedAt() { return createdAt; }
    public void setCreatedAt(Instant createdAt) { this.createdAt = createdAt; }

    public Instant getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(Instant updatedAt) { this.updatedAt = updatedAt; }
}
