package com.skillforge.server.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.Instant;

/**
 * Dynamic bash/node hook method generated by Code Agent.
 *
 * <p>On startup, enabled rows are wrapped as {@code BuiltInMethod} instances and registered
 * into {@code BuiltInMethodRegistry} under the {@code agent.*} namespace.
 */
@Entity
@Table(name = "t_script_method")
@EntityListeners(AuditingEntityListener.class)
public class ScriptMethodEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Unique lookup key, must start with "agent.". */
    @Column(nullable = false, unique = true, length = 128)
    private String ref;

    @Column(name = "display_name", nullable = false, length = 256)
    private String displayName;

    @Column(columnDefinition = "TEXT")
    private String description;

    /** "bash" | "node" */
    @Column(nullable = false, length = 32)
    private String lang;

    @Column(name = "script_body", nullable = false, columnDefinition = "TEXT")
    private String scriptBody;

    /** JSON object describing argument types. */
    @Column(name = "args_schema", columnDefinition = "TEXT")
    private String argsSchema;

    @Column(name = "owner_id")
    private Long ownerId;

    @Column(nullable = false)
    private boolean enabled = true;

    @CreatedDate
    @Column(name = "created_at")
    private Instant createdAt;

    @LastModifiedDate
    @Column(name = "updated_at")
    private Instant updatedAt;

    public ScriptMethodEntity() {
    }

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getRef() { return ref; }
    public void setRef(String ref) { this.ref = ref; }

    public String getDisplayName() { return displayName; }
    public void setDisplayName(String displayName) { this.displayName = displayName; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public String getLang() { return lang; }
    public void setLang(String lang) { this.lang = lang; }

    public String getScriptBody() { return scriptBody; }
    public void setScriptBody(String scriptBody) { this.scriptBody = scriptBody; }

    public String getArgsSchema() { return argsSchema; }
    public void setArgsSchema(String argsSchema) { this.argsSchema = argsSchema; }

    public Long getOwnerId() { return ownerId; }
    public void setOwnerId(Long ownerId) { this.ownerId = ownerId; }

    public boolean isEnabled() { return enabled; }
    public void setEnabled(boolean enabled) { this.enabled = enabled; }

    public Instant getCreatedAt() { return createdAt; }
    public void setCreatedAt(Instant createdAt) { this.createdAt = createdAt; }

    public Instant getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(Instant updatedAt) { this.updatedAt = updatedAt; }
}
