-- P4 Phase 1: Script methods — Code Agent generated bash/node hook methods
CREATE TABLE t_script_method (
    id           BIGSERIAL PRIMARY KEY,
    ref          VARCHAR(128) NOT NULL UNIQUE,
    display_name VARCHAR(256) NOT NULL,
    description  TEXT,
    lang         VARCHAR(32) NOT NULL,
    script_body  TEXT NOT NULL,
    args_schema  TEXT,
    owner_id     BIGINT,
    enabled      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ,
    updated_at   TIMESTAMPTZ
);

CREATE INDEX idx_script_method_enabled ON t_script_method(enabled);
CREATE INDEX idx_script_method_owner   ON t_script_method(owner_id);

COMMENT ON TABLE t_script_method IS
    'Dynamically registered bash/node hook methods, generated by Code Agent. ref must start with "agent." (builtin.* reserved for @Component beans).';
COMMENT ON COLUMN t_script_method.ref IS 'Unique lookup key, e.g. "agent.slack-token-report". Registered into BuiltInMethodRegistry at startup.';
COMMENT ON COLUMN t_script_method.lang IS '"bash" or "node"';
COMMENT ON COLUMN t_script_method.args_schema IS 'JSON object describing argument types for the frontend';
