-- Existing paired phones should gain the same read-only Agent scope as new pairings.
-- scopes_json is generated by SkillForge and is therefore valid JSON.
UPDATE t_mobile_device
SET scopes_json = (
    SELECT jsonb_agg(scope ORDER BY scope)::text
    FROM (
        SELECT DISTINCT jsonb_array_elements_text(
            scopes_json::jsonb || '["agent:read"]'::jsonb
        ) AS scope
    ) expanded_scopes
)
WHERE platform = 'ios'
  AND status = 'active'
  AND NOT scopes_json::jsonb @> '["agent:read"]'::jsonb;
